//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synchronic_World.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        public Event()
        {
            this.participatingUser = new HashSet<User>();
            this.eventContribution = new HashSet<Contribution>();
        }

        public int Id { get; set; }
        [Required]
        public string name { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string desc { get; set; }

        [Required]
        public string adress { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime date { get; set; }
        public string hour { get; set; }
        public int type { get; set; }
        public string status { get; set; }

        public virtual ICollection<User> participatingUser { get; set; }
        public virtual ICollection<Contribution> eventContribution { get; set; }
    }
}
