//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synchronic_World.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.participatingEvent = new HashSet<Event>();
            this.Contribution = new HashSet<Contribution>();
        }

        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime birthday { get; set; }

        [Required]
        public string mail { get; set; }

        [Required]
        public string password { get; set; }
        public string role { get; set; }

        public virtual ICollection<Event> participatingEvent { get; set; }
        public virtual ICollection<Contribution> Contribution { get; set; }
    }
}
